### ISSUE TITLE
cannot run bct util on 'Linux Mint 18 Sarah'

### ISSUE THREAD

**Issue by oe5hpm** [IntelFsp/BCT#2]
The tool quits with:

`Traceback (most recent call last):
  File "<string>", line 42, in <module>
  File "C:\Git\fsp_bootloader-bct\bct\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 386, in importHook
  File "C:\Git\fsp_bootloader-bct\bct\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 480, in doimport
  File "/mnt/hgfs/Fedora24ShareVMP/bct331release/bct/install/fc14/64bit/build/pyi.linux2/bct/out00-PYZ.pyz/cmdlineparse", line 48, in <module>
  File "C:\Git\fsp_bootloader-bct\bct\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 386, in importHook
  File "C:\Git\fsp_bootloader-bct\bct\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 480, in doimport
  File "/mnt/hgfs/Fedora24ShareVMP/bct331release/bct/install/fc14/64bit/build/pyi.linux2/bct/out00-PYZ.pyz/version", line 27, in <module>
  File "C:\Git\fsp_bootloader-bct\bct\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 386, in importHook
  File "C:\Git\fsp_bootloader-bct\bct\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 480, in doimport
  File "/mnt/hgfs/Fedora24ShareVMP/bct331release/bct/install/fc14/64bit/build/pyi.linux2/bct/out00-PYZ.pyz/locales.stringtable", line 28, in <module>
  File "C:\Git\fsp_bootloader-bct\bct\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 386, in importHook
  File "C:\Git\fsp_bootloader-bct\bct\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 480, in doimport
  File "/mnt/hgfs/Fedora24ShareVMP/bct331release/bct/install/fc14/64bit/build/pyi.linux2/bct/out00-PYZ.pyz/wx", line 45, in <module>
  File "C:\Git\fsp_bootloader-bct\bct\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 386, in importHook
  File "C:\Git\fsp_bootloader-bct\bct\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 480, in doimport
  File "/mnt/hgfs/Fedora24ShareVMP/bct331release/bct/install/fc14/64bit/build/pyi.linux2/bct/out00-PYZ.pyz/wx._core", line 4, in <module>
  File "C:\Git\fsp_bootloader-bct\bct\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 386, in importHook
  File "C:\Git\fsp_bootloader-bct\bct\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 449, in doimport
  File "C:\Git\fsp_bootloader-bct\bct\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 248, in getmod
  File "C:\Git\fsp_bootloader-bct\bct\tools\pyinstaller-2.0\PyInstaller\loader\archive.py", line 495, in getmod
  File "C:\Git\fsp_bootloader-bct\bct\tools\pyinstaller-2.0\PyInstaller\loader\iu.py", line 105, in getmod
ImportError: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: undefined symbol: drmGetDevices2
`
running system here is:
schmelzerh@ategge3722 ~/work/x20apl/bct $ cat /etc/deb
debconf.conf    debian_version  
schmelzerh@ategge3722 ~/work/x20apl/bct $ cat /etc/debian_version 
stretch/sid
schmelzerh@ategge3722 ~/work/x20apl/bct $ uname -a
Linux ategge3722 4.11.0-14-generic #20~16.04.1-Ubuntu SMP Wed Aug 9 09:06:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
schmelzerh@ategge3722 ~/work/x20apl/bct $

**Comment by nate-desimone** [comment]
Hi,

Linux Mint isn't officially supported, but you might have more luck with the new 3.4.0 release: https://github.com/IntelFsp/BCT/raw/master/bct-3.4.0-x86_64.ubuntu16.04.tar.gz
